#!/bin/sh
# Credits
#
# https://github.com/junnunkarim/dotfiles-linux
#

# Directory
dwm_dir="$HOME/.config/dwm"
dmenu_dir="$HOME/.config/dmenu"
st_dir="$HOME/.config/st"
zathura_dir="$HOME/.config/zathura"

change_theme()
{
	cp ${dwm_dir}/$1 ${dwm_dir}/theme
	cp ${dmenu_dir}/$1 ${dmenu_dir}/theme
	cp ${st_dir}/$1 ${st_dir}/theme
	cp ${zathura_dir}/theme/$1 ${zathura_dir}/theme.color
	
	xrdb -merge -I$HOME ~/.config/X11/Xresources # reload Xresources

  # calls xrdb function in dwm
  kill -HUP $(pidof dwm)

  # update st
  kill -USR1 $(pidof st)

}
change_gtk_theme() 
{
   sed -e "s/^gtk-theme-name=.*/gtk-theme-name="$@"/" -i ~/.config/gtk-3.0/settings.ini
   sed -e "s/^gtk-theme-name=.*/gtk-theme-name=\""$@"\"/" -i ~/.config/gtk-2.0/gtkrc
}
change_vim_theme()
{
  sed -i "s/colorscheme\ .*/colorscheme\ "$1"/" ~/.config/vim/init/plugins.vim
}
change_neovim_theme()
{
  # sed -i "s/colorscheme\ [^\]]*/colorscheme\ "$1"/" ~/.config/nvim/lua/user/colorscheme.lua
  sed -i "s/\[\[colorscheme\ .*\]\]/\[\[colorscheme $1\]\]/" ~/.config/nvim/lua/user/colorscheme.lua
}
change_nitrogen_theme()
{
  sed -i "s|file=.*|file=$@|" ~/.config/nitrogen/bg-saved.cfg

  nitrogen --restore
}

# Theme
cancel="窱 Cancel"
theme1=" Dracula"
theme2=" Gruvbox"
theme3=" Nord"
theme4=" Tokyo Night"

# Variable to pass to dmenu or rofi
option="$cancel\n$theme1\n$theme2\n$theme3\n$theme4\n$theme5\n$theme6\n$theme7"

select="$(echo -e "$option" | dmenu -p "Choose a theme" )"

case $select in
	$theme1)
		# feh --random --bg-fill $HOME/.config/wallpaper/dracula
    wallpaper=$(shuf -e $(ls -d -1 ~/.config/wallpaper/dracula/* | cut -d' ' -f10 ) | head -n1)
    change_nitrogen_theme $wallpaper
		change_gtk_theme dracula-gtk
		change_vim_theme dracula
		change_neovim_theme dracula
		change_theme dracula
		;;
	$theme2)
		# feh --random --bg-fill $HOME/.config/wallpaper/gruvbox
    wallpaper=$(shuf -e $(ls -d -1 ~/.config/wallpaper/gruvbox/* | cut -d' ' -f10 ) | head -n1)
    change_nitrogen_theme $wallpaper
		change_gtk_theme gruvbox-dark-gtk
		change_vim_theme gruvbox
		change_neovim_theme gruvbox-baby
		change_theme gruvbox
		;;
	$theme3)
		# feh --random --bg-fill $HOME/.config/wallpaper/nord
    wallpaper=$(shuf -e $(ls -d -1 ~/.config/wallpaper/nord/* | cut -d' ' -f10 ) | head -n1)
    change_nitrogen_theme $wallpaper
		change_theme nord
		change_vim_theme nord
		change_neovim_theme nord
		change_gtk_theme nord-gtk
		;;
	$theme4)
		# feh --random --bg-fill $HOME/.config/wallpaper/nord
    wallpaper=$(shuf -e $(ls -d -1 ~/.config/wallpaper/tokyo-night/* | cut -d' ' -f10 ) | head -n1)
    change_nitrogen_theme $wallpaper
		change_theme tokyonight
		change_vim_theme tokyonight
		change_neovim_theme tokyonight
		change_gtk_theme tokyonight-gtk
		;;
esac
